# Generated by Django 5.2.17 on 2026-08-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entreprise',
            options={'ordering': ['nom'], 'permissions': [('manage_users', 'Peut gérer les utilisateurs'), ('manage_roles', 'Peut gérer les rôles'), ('manage_entreprises', 'Peut gérer les entreprises')]},
        ),
    ]
