# Generated by Django 5.2.17 on 2026-08-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_entreprise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_users', 'Peut gérer les utilisateurs')]},
        ),
    ]
