# Generated by Django 5.2.16 on 2026-09-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='is_active',
            new_name='actif',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='matricule_fiscale',
            new_name='matricule_fiscal',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='code',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entreprises/logos/'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
