# Generated by Django 5.2.16 on 2026-09-10 02:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_permission_rename_created_at_user_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='date_demande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='est_admin_entreprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='statut_compte',
            field=models.CharField(choices=[('en_attente_validation', 'En attente de validation'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='en_attente_validation', max_length=30),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
