# Generated by Django 5.2.16 on 2026-09-17 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar_user_two_factor_backup_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='delai_alerte_expiration_jours',
            field=models.IntegerField(default=15, help_text="Délai d'alerte en jours avant l'expiration d'un contrat"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='destinataires_alertes',
            field=models.CharField(choices=[('admin_uniquement', 'Administrateurs uniquement'), ('responsables_et_admin', 'Responsables et administrateurs'), ('tous', 'Tous les utilisateurs')], default='responsables_et_admin', max_length=50),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_email_contrats', models.BooleanField(default=True)),
                ('notif_email_mouvements', models.BooleanField(default=True)),
                ('notif_email_amortissements', models.BooleanField(default=True)),
                ('notif_email_interventions', models.BooleanField(default=True)),
                ('notif_inapp_enabled', models.BooleanField(default=True)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية')], default='fr', max_length=10)),
                ('theme', models.CharField(choices=[('clair', 'Clair'), ('sombre', 'Sombre')], default='clair', max_length=20)),
                ('devise', models.CharField(choices=[('TND', 'TND (DT)'), ('EUR', 'EUR (€)'), ('USD', 'USD ($)')], default='TND', max_length=10)),
                ('items_par_page', models.IntegerField(choices=[(10, '10 par page'), (25, '25 par page'), (50, '50 par page')], default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
    ]
