# Generated by Django 5.2.16 on 2026-09-09 00:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immobilisations', '0002_planamortissement_ecritureamortissement'),
        ('users', '0005_permission_rename_created_at_user_date_creation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('fournisseur', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective')], default='preventive', max_length=50)),
                ('periodicite', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('annuelle', 'Annuelle')], default='mensuelle', max_length=50)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='actif', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_maintenance', to='users.entreprise')),
            ],
            options={
                'db_table': 'contrats_maintenance',
                'ordering': ['-date_debut'],
                'unique_together': {('entreprise', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_alerte', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut_lecture', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu')], default='non_lu', max_length=50)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='maintenance.contratmaintenance')),
            ],
            options={
                'db_table': 'alertes_maintenance',
                'ordering': ['-date_alerte'],
            },
        ),
        migrations.CreateModel(
            name='DocumentContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='contrats/documents/')),
                ('nom', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='maintenance.contratmaintenance')),
            ],
            options={
                'db_table': 'documents_contrats',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField(default=django.utils.timezone.now)),
                ('type_intervention', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('technicien', models.CharField(blank=True, max_length=255)),
                ('cout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('statut', models.CharField(choices=[('planifie', 'Planifiée'), ('en_cours', 'En cours'), ('realise', 'Réalisée'), ('annule', 'Annulée')], default='planifie', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='maintenance.contratmaintenance')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='immobilisations.immobilisation')),
            ],
            options={
                'db_table': 'interventions_maintenance',
                'ordering': ['-date_intervention'],
            },
        ),
        migrations.CreateModel(
            name='ImmobilisationContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilisations_contrat', to='maintenance.contratmaintenance')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_immobilisation', to='immobilisations.immobilisation')),
            ],
            options={
                'db_table': 'immobilisations_contrats',
                'unique_together': {('contrat', 'immobilisation')},
            },
        ),
    ]
