# Generated by Django 5.2.16 on 2026-09-17 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0002_planamortissement_ecritureamortissement'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='immobilisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='immobilisations.immobilisation'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='lien_cible',
            field=models.CharField(blank=True, help_text='Redirection interne (ex: /maintenance)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('expiration_contrat', 'Expiration de contrat'), ('mouvement', "Mouvement d'emplacement"), ('amortissement', 'Amortissement'), ('maintenance', 'Intervention de maintenance'), ('autre', 'Autre alerte')], default='expiration_contrat', max_length=100),
        ),
    ]
