# Generated by Django 5.2.17 on 2026-09-09 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_permission_rename_created_at_user_date_creation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_emplacement', models.CharField(max_length=100)),
                ('nom_emplacement', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bureau', 'Bureau'), ('depot', 'Dépôt'), ('chantier', 'Chantier'), ('agence', 'Agence')], default='bureau', max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='users.entreprise')),
            ],
            options={
                'db_table': 'emplacements',
                'ordering': ['nom_emplacement'],
                'unique_together': {('entreprise', 'code_emplacement')},
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles', to='users.entreprise')),
            ],
            options={
                'db_table': 'familles',
                'ordering': ['nom'],
                'unique_together': {('entreprise', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_inventaire', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fournisseur', models.CharField(blank=True, max_length=255)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('valeur_acquisition', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('hors_service', 'Hors service')], default='neuf', max_length=50)),
                ('statut', models.CharField(choices=[('en_service', 'En service'), ('en_maintenance', 'En maintenance'), ('reforme', 'Réformé'), ('cede', 'Cédé')], default='en_service', max_length=50)),
                ('date_mise_en_service', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='immobilisations/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emplacement_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immobilisations', to='immobilisations.emplacement')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilisations', to='users.entreprise')),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immobilisations', to='immobilisations.famille')),
            ],
            options={
                'db_table': 'immobilisations',
                'ordering': ['-created_at'],
                'unique_together': {('entreprise', 'code_inventaire')},
            },
        ),
        migrations.CreateModel(
            name='MouvementEmplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('ancien_emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_anciens', to='immobilisations.emplacement')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_emplacement', to='immobilisations.immobilisation')),
                ('nouvel_emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_nouveaux', to='immobilisations.emplacement')),
                ('responsable_transfert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_effectues', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_concernes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mouvements_emplacement',
                'ordering': ['-date_transfert'],
            },
        ),
    ]
