# Generated by Django 5.2.16 on 2026-09-09 00:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAmortissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_acquisition', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_debut_amortissement', models.DateField()),
                ('duree_amortissement', models.PositiveIntegerField(help_text='Durée en années')),
                ('taux_amortissement', models.DecimalField(decimal_places=2, help_text='Taux annuel en pourcentage (%)', max_digits=5)),
                ('mode_amortissement', models.CharField(choices=[('lineaire', 'Linéaire'), ('degressif', 'Dégressif')], default='lineaire', max_length=20)),
                ('valeur_residuelle', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('immobilisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_amortissement', to='immobilisations.immobilisation')),
            ],
            options={
                'db_table': 'plans_amortissement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcritureAmortissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercice', models.PositiveIntegerField()),
                ('annuite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amortissement_cumule', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valeur_nette_comptable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_calcul', models.DateField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='immobilisations.planamortissement')),
            ],
            options={
                'db_table': 'ecritures_amortissement',
                'ordering': ['exercice'],
            },
        ),
    ]
