# Generated by Django 5.2.17 on 2026-09-17 22:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0002_planamortissement_ecritureamortissement'),
        ('users', '0009_historicaluser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmplacement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code_emplacement', models.CharField(max_length=100)),
                ('nom_emplacement', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bureau', 'Bureau'), ('depot', 'Dépôt'), ('chantier', 'Chantier'), ('agence', 'Agence')], default='bureau', max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entreprise', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.entreprise')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical emplacement',
                'verbose_name_plural': 'historical emplacements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalImmobilisation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code_inventaire', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fournisseur', models.CharField(blank=True, max_length=255)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('valeur_acquisition', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('hors_service', 'Hors service')], default='neuf', max_length=50)),
                ('statut', models.CharField(choices=[('en_service', 'En service'), ('en_maintenance', 'En maintenance'), ('reforme', 'Réformé'), ('cede', 'Cédé')], default='en_service', max_length=50)),
                ('date_mise_en_service', models.DateField(blank=True, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('emplacement_actuel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='immobilisations.emplacement')),
                ('entreprise', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.entreprise')),
                ('famille', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='immobilisations.famille')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical immobilisation',
                'verbose_name_plural': 'historical immobilisations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
