# Generated by Django 5.2.17 on 2026-09-18 14:49

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0004_historicalfamille'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlanAmortissement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('valeur_acquisition', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_debut_amortissement', models.DateField()),
                ('duree_amortissement', models.PositiveIntegerField(help_text='Durée en années')),
                ('taux_amortissement', models.DecimalField(decimal_places=2, help_text='Taux annuel en pourcentage (%)', max_digits=5)),
                ('mode_amortissement', models.CharField(choices=[('lineaire', 'Linéaire'), ('degressif', 'Dégressif')], default='lineaire', max_length=20)),
                ('valeur_residuelle', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('immobilisation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='immobilisations.immobilisation')),
            ],
            options={
                'verbose_name': 'historical plan amortissement',
                'verbose_name_plural': 'historical plan amortissements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
